### ISSUE TITLE
Aparecen Anuncios en YouTube

### ISSUE THREAD

**Issue by Solus32** [astrolince/hosty#19]
Hola @astrolince estuve probando tu versión de hosty v1.6.2, pero en youtube salen anuncios dentro del vídeo, lo estuve verificando con algunos vídeos como en Dying Light 2.

![anuncio youtube](https://user-images.githubusercontent.com/27927896/56868760-8d7c1c00-69bc-11e9-917c-9f658ff89ba9.png)

**Comment by astrolince** [comment]
Hola @Solus32, hay 3 consideraciones a tener en cuenta:

1) Es muy dificil eliminar todos los anuncios de Youtube a punta de bloquear dominios en el archivo hosts del sistema, Youtube es bastante sofisticado con su forma de mostrarlos, hosty funciona exclusivamente a través de ese mecanismo, esto tiene pros como su eficiencia y alcance a todo el sistema, y contras como su irremediable imperfección como único metodo para bloquear ads.

Considero recomendable usar uBlock Origin o el navegador Brave.

2) Por defecto hosty no viene configurado para ser super agresivo, intento hacer un balance buscando ofrecer un bloqueo estándar que limite consecuencias inesperadas como romper sitios webs a una base de usuarios previsiblemente diversa. Pero tampoco recomiendo intentar agregar un monton de listas adicionales y eliminar las whitelists intentando bloquear los ads de youtube, no daria un resultado muy satisfactorio.

Podes probar agregar algo como:

https://raw.githubusercontent.com/Akamaru/Pi-Hole-Lists/master/youtube.txt
https://raw.githubusercontent.com/anudeepND/youtubeadsblacklist/master/domainlist.txt
https://gist.githubusercontent.com/Ewpratten/a25ae63a7200c02c850fede2f32453cf/raw/d19b6edd63cbd9154d20dce782198920c3bb770e/hosts-yt-ads
https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/ParsedBlacklists/Henning-VanRaumle-Youtube.txt
https://raw.githubusercontent.com/CitizenXVIL/Hosts/master/Youtube%20hosts.txt
https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/ParsedBlacklists/Anudeep-Youtube.txt
https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/ParsedBlacklists/Adblock-YouTube-Ads.txt

en /etc/hosty/blacklist.sources

https://filterlists.com/ tiene una gran lista de listas para mirar

3) Youtube ofrece en algunos paises un método propio para eliminar la publicidad mediante su suscripción premium, no se puede olvidar que el bloqueo de anuncios causa que tu vista no genere dinero al creador del contenido, cosa que la suscripción permite, por lo que no está libre de consecuencias. Si la generación del contenido que te gusta no es incentivada económicamente, a la larga o a la corta su sostenibilidad tendrá problemas o su calidad caerá fuertemente. Los anuncios están siendo parte directa de los vídeo cada vez con mayor frecuencia, si el creador tiene la ventaja de conseguir sponsors directos.

**Comment by Solus32** [comment]
ok muchas gracias, saludos
