### ISSUE TITLE
Blocked sites

### ISSUE THREAD

**Issue by Predatux** [astrolince/hosty#22]
I have a little problem with hosty.
Hosty blocks certain pages, such as:

https://www.teslarati.com/
https://forms.gle/

I searched for those entries in /etc/hosts and there is no trace of them.
I created the /etc/hosty directory and inside it, I created the "whitelist" archive.
I added as you indicate one entry per line:
https://www.teslarati.com/
www.teslarati.com/
https://forms.gle/
forms.gle

But after saving changes, the system keeps blocking theese pages.
Restoring hosty, the pages are viewed correctly.

Can you tell me what I'm doing wrong?
Thank you

**Comment by astrolince** [comment]
I can access both sites without problems but we can try things,
your "/etc/hosty/whitelist" shouls look like this:
teslarati.com
www.teslarati.com
forms.gle
www.forms.gle

After that, run again $ sudo hosty.
