### ISSUE TITLE
Add support for doas

### ISSUE THREAD

**Issue by leorockway** [astrolince/hosty#24]
The installer requires sudo. It won't even work if it's manually ran by root. Having the option of being able to run it as root or using doas would be great.

**Comment by astrolince** [comment]
You're right the install.sh follows a different design, updater.sh and hosty.sh are just fine, I'll fix that.

**Comment by astrolince** [comment]
I have removed sudo as a dependence, could you try it now?

**Comment by leorockway** [comment]
curl -L git.io/hosty | sh doesn't work because the script doesn't know how to escalate privileges. Downloading it and either running it as root or with doas works fine, though, whereas before it wasn't possible.

**Comment by astrolince** [comment]
I have tested it in every possible situation...

If you are log in as root, just run:

curl -L git.io/hosty | sh

that will work if you have sudo or not

If your aren't root, but you have sudo,  run:

curl -L git.io/hosty | sh

the scripts will escalate privileges automatically

But you aren't root and you just have doas, the script will not recognize that, so you need to exec it like this:

curl -Ls git.io/hosty | doas sh

also notice that you may be downloading a cached script, try to replace git.io/hosty with "git.io/hosty?randomstring123"

I'll wait your feedback

**Comment by leorockway** [comment]
> But if you aren't root and you just have doas, the script will not recognize that
Right, that's what I meant.

But I do confirm that these two work fine and as expected now:

As root:
# curl -L git.io/hosty | sh

As a user:
% curl -Ls git.io/hosty | doas sh

**Comment by astrolince** [comment]
Cool, that's the expected behavior so I'll declare this fixed.

Have a nice day!
