### ISSUE TITLE
Update installation-instructions for SailfishOS 4.4.0.64

### ISSUE THREAD

**Issue by speedy-10** [astrolince/hosty#32]
Hi, I just tried to install and start hosty on a Xperia 10 III with SailfishOS.

Please add the following 2 information in your READ.me file:

Additional steps to install hosty in Sailfish OS

During installation hosty will ask if you want to automatically run hosty from time to time to update your hosts file with the latest list of domains.

We answer the following questions:

Do you want to always run the latest version of hosty? Y

Do you want to automatically update your hosts file with latest ads list? n

Once hosty ends its installation, just run again:

$ curl -L git.io/hosty | sh
Extend Ad Blocking to Sailfish OS Android App Support

Add this line to /var/lib/lxc/aliendalvik/extra_config (create the file if it doesn't exist):

$ sudo nano /var/lib/lxc/aliendalvik/extra_config

lxc.mount.entry = /etc/hosts system/etc/hosts none bind,create=file 0 0

-> **Restart your phone.**

-> **On SailfishOS you need to `devel-su pkcon remove busybox-symlinks-bash` to install gnu-bash, which is actual necessary to execute the next command `sudo hosty'.** (With busybox the command ends in an error message.)

(See also: -> [Forum](https://forum.sailfishos.org/t/support-for-addons-on-the-browser/3587/31))

**Comment by astrolince** [comment]
Hi, so "devel-su zypper install gnu-bash" doesn't install gnu-bash but you need to do "devel-su pkcon remove busybox-symlinks-bash"?

**Comment by speedy-10** [comment]
Hi, I just only tried "devel-su pkcon remove busybox-symlinks-bash", which was mentioned in the forum. Perhaps another user vould the the other command.

**Comment by astrolince** [comment]
Then you didn't followed the readme, "devel-su zypper install gnu-bash" is in the "Install the requeriments" part

**Comment by speedy-10** [comment]
So far I remember I followed your  "Install the requeriments" line by line, but I can't control it - the new history of bash is empty.

**Comment by speedy-10** [comment]
Hi, I now remember that after typing "devel-su zypper install gnu-bash" I was asked (because of some system-changings that was new for me) to decide between (N/y), I chose N.
Nevertheless, the restart before "sudo hosty" is necessary, this could be mentioned in your README.md.
