### ISSUE TITLE
cannot install via curl

### ISSUE THREAD

**Issue by scarf005** [astrolince/hosty#65]
```sh
$ curl -L git.io/hosty
$ curl -L git.io/hosty | cat
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
$ curl -L git.io/hosty
$
```

I think `git.io/hosty` on [installation](https://github.com/astrolince/hosty#install-hosty) isn't returning any text.

**Comment by astrolince** [comment]
Currently, it works for me, I don't know if it may be a problem with your device or network, or if git.io went temporally down, either way you can always directly use https://raw.githubusercontent.com/astrolince/hosty/master/install.sh
