### ISSUE TITLE
Can't find the etc/hosty

### ISSUE THREAD

**Issue by vybhav-ibr** [astrolince/hosty#69]
Installed hosty recently on my system running ubuntu 20.04 .
I want to add youtube.com to my blacklist and i can't find the _/etc/hosty/blacklist_
Infact I can't even find the /hosty folder in _'etc'_.
I tried using the find function via the terminal and the file explorer the only result for hosty was the _hosty.sh_ file in the _usr/local/bin_ directory.
I even tried adding the entry manually to the _hosts_ file in _etc_ using a text editor, but i am not able to save the file, as it is read-only.
Let me know how websites can be added to the blacklist
![image](https://github.com/astrolince/hosty/assets/119930636/998f657b-587d-40a1-88eb-1cd4a5e035d2)

**Comment by astrolince** [comment]
Just create it

$ sudo mkdir /etc/hosty

$ sudo touch /etc/hosty/blacklist

**Comment by astrolince** [comment]
In /etc
