### ISSUE TITLE
signature problem

### ISSUE THREAD

**Issue by omid455** [astrolince/hosty#74]
I get the following error when trying to install on mac os big sur:
"there is a problem with the signature, probably hosty repository was compromised, no changes were made to your system."

install method:
curl -L https://astrolince.com/hosty/install.sh | sh

**Comment by astrolince** [comment]
Reinstall answering "n" to "do you want to always run the latest version of hosty? (recommended) y/n"

**Comment by omid455** [comment]
> Reinstall answering "n" to "do you want to always run the latest version of hosty? (recommended) y/n"

Thanks! solved the issue.

**Comment by omid455** [comment]
Thanks for this great software and quick support!
